apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: monitoring
data:
  default.tmpl: |
    {{ define "__subject" }}
    [{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}
    {{ end }}

    {{ define "__description" }}
    {{ range .Alerts }}
    Alert: {{ .Annotations.summary }}
    Description: {{ .Annotations.description }}
    Severity: {{ .Labels.severity }}
    Instance: {{ .Labels.instance }}
    {{ if .Annotations.runbook_url }}
    Runbook: {{ .Annotations.runbook_url }}
    {{ end }}
    {{ end }}
    {{ end }}

    {{ define "slack.default.title" }}
    {{ if eq .Status "firing" }}🚨 {{ end }}{{ if eq .Status "resolved" }}✅ {{ end }}{{ .GroupLabels.alertname }}
    {{ end }}

    {{ define "slack.default.text" }}
    {{ range .Alerts }}
    *Alert:* {{ .Annotations.summary }}
    *Description:* {{ .Annotations.description }}
    *Severity:* {{ .Labels.severity }}
    *Instance:* {{ .Labels.instance }}
    *Started:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
    {{ if .Annotations.runbook_url }}
    *Runbook:* {{ .Annotations.runbook_url }}
    {{ end }}
    {{ end }}
    {{ end }}

    {{ define "email.default.subject" }}
    {{ template "__subject" . }}
    {{ end }}

    {{ define "email.default.html" }}
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; }
            .header { background-color: #f8f9fa; padding: 20px; border-left: 4px solid #dc3545; }
            .content { padding: 20px; }
            .alert { margin-bottom: 20px; padding: 15px; border-radius: 5px; }
            .critical { background-color: #f8d7da; border-left: 4px solid #dc3545; }
            .warning { background-color: #fff3cd; border-left: 4px solid #ffc107; }
            .info { background-color: #d1ecf1; border-left: 4px solid #17a2b8; }
            .footer { background-color: #f8f9fa; padding: 10px; font-size: 12px; color: #6c757d; }
        </style>
    </head>
    <body>
        <div class="header">
            <h2>{{ template "__subject" . }}</h2>
        </div>
        <div class="content">
            {{ range .Alerts }}
            <div class="alert {{ .Labels.severity }}">
                <h3>{{ .Annotations.summary }}</h3>
                <p><strong>Description:</strong> {{ .Annotations.description }}</p>
                <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
                <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
                <p><strong>Started:</strong> {{ .StartsAt.Format "2006-01-02 15:04:05" }}</p>
                {{ if .Annotations.runbook_url }}
                <p><strong>Runbook:</strong> <a href="{{ .Annotations.runbook_url }}">{{ .Annotations.runbook_url }}</a></p>
                {{ end }}
            </div>
            {{ end }}
        </div>
        <div class="footer">
            <p>This alert was generated by Prometheus Alertmanager</p>
        </div>
    </body>
    </html>
    {{ end }}
