apiVersion: v2
name: devops-app
description: A Helm chart for DevOps End-to-End Demo Application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - devops
  - nodejs
  - express
  - monitoring
home: https://github.com/your-org/devops-end2end
sources:
  - https://github.com/your-org/devops-end2end
maintainers:
  - name: DevOps Team
    email: devops@company.com
dependencies:
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "7.0.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
